default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: news_room_development

test: &test
  <<: *default
  database: news_room_test

production:
  <<: *default
  database: news_room_production
  username: news_room
  password: <%= ENV['NEWS_ROOM_DATABASE_PASSWORD'] %>

cucumber:
  <<: *test
